# Generated by Django 2.2.2 on 2019-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('word1', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord1', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart1', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd1', models.CharField(blank=True, default=None, max_length=1000)),
                ('word2', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord2', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart2', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd2', models.CharField(blank=True, default=None, max_length=1000)),
                ('word3', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord3', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart3', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd3', models.CharField(blank=True, default=None, max_length=1000)),
                ('word4', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord4', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart4', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd4', models.CharField(blank=True, default=None, max_length=1000)),
                ('word5', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord5', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart5', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd5', models.CharField(blank=True, default=None, max_length=1000)),
                ('word6', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord6', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart6', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd6', models.CharField(blank=True, default=None, max_length=1000)),
                ('word7', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord7', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart7', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd7', models.CharField(blank=True, default=None, max_length=1000)),
                ('word8', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord8', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart8', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd8', models.CharField(blank=True, default=None, max_length=1000)),
                ('word9', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord9', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart9', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd9', models.CharField(blank=True, default=None, max_length=1000)),
                ('word10', models.CharField(blank=True, default=None, max_length=1000)),
                ('translatedWord10', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceStart10', models.CharField(blank=True, default=None, max_length=1000)),
                ('sentenceEnd10', models.CharField(blank=True, default=None, max_length=1000)),
            ],
        ),
    ]
