# Generated by Django 2.2.2 on 2019-06-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragdrop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='title',
        ),
    ]
