# Generated by Django 2.2.2 on 2019-06-07 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dragdrop', '0002_remove_word_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
